from typing import TYPE_CHECKING, Any, Dict, List, Optional

if TYPE_CHECKING:

    class ClientMixin:
        """
        Typing-only contract shared by mixins.

        Runtime mixin composition still happens in ``aiograpi.Client``. This
        class only tells static checkers about shared attributes, request
        helpers, and cross-mixin integration points so feature code can use
        normal ``self.foo`` access.
        """

        android_device_id: str
        authorization_data: Dict[str, Any]
        bloks_versioning_id: str
        challenge_code_handler: Any
        change_password_handler: Any
        client_session_id: str
        country: str
        country_code: int
        delay_range: Optional[List[int]]
        device_settings: Dict[str, Any]
        domain: str
        email: Optional[str]
        graphql: Any
        handle_exception: Any
        ig_u_rur: Optional[str]
        ig_www_claim: Optional[str]
        last_json: Dict[str, Any]
        last_response: Any
        locale: str
        logger: Any
        mid: str
        num_retry: int
        password: str
        phone_id: str
        phone_number: Optional[str]
        private: Any
        private_requests_count: int
        public: Any
        public_accept_language: str
        public_transport: str
        public_transport_impersonate: str
        public_user_agent: str
        read_timeout: int
        request_id: str
        request_timeout: int
        settings: Dict[str, Any]
        timezone_offset: int
        tray_session_id: str
        user_agent: str
        username: str
        uuid: str
        with_challenge_flow: bool

        @property
        def authorization(self) -> str: ...

        @property
        def base_headers(self) -> Dict[str, Any]: ...

        @property
        def cookie_dict(self) -> Dict[str, Any]: ...

        @property
        def device(self) -> Dict[str, Any]: ...

        @property
        def fb_dtsg(self) -> Any: ...

        @property
        def rank_token(self) -> str: ...

        @property
        def sessionid(self) -> str: ...

        @property
        def token(self) -> str: ...

        @property
        def user_id(self) -> int: ...

        def _extract_configured_direct_message_or_raise(self, *args: Any, **kwargs: Any) -> Any: ...

        def _extract_configured_media_or_raise(self, *args: Any, **kwargs: Any) -> Any: ...

        async def _feed_music_params(self, *args: Any, **kwargs: Any) -> Dict[str, Any]: ...

        async def _send_private_request(self, *args: Any, **kwargs: Any) -> Any: ...

        async def bloks_action(self, *args: Any, **kwargs: Any) -> Any: ...

        async def bloks_change_password(self, *args: Any, **kwargs: Any) -> Any: ...

        async def challenge_resolve(self, *args: Any, **kwargs: Any) -> Any: ...

        async def expose(self, *args: Any, **kwargs: Any) -> Any: ...

        def gen_user_breadcrumb(self, *args: Any, **kwargs: Any) -> str: ...

        def generate_android_device_id(self, *args: Any, **kwargs: Any) -> str: ...

        def generate_mutation_token(self, *args: Any, **kwargs: Any) -> str: ...

        def generate_uuid(self, *args: Any, **kwargs: Any) -> str: ...

        async def graphql_request(self, *args: Any, **kwargs: Any) -> Any: ...

        def inject_sessionid_to_public(self, *args: Any, **kwargs: Any) -> Any: ...

        async def location_build(self, *args: Any, **kwargs: Any) -> Any: ...

        async def location_complete(self, *args: Any, **kwargs: Any) -> Any: ...

        def location_story_sticker_id(self, *args: Any, **kwargs: Any) -> Any: ...

        async def media_configure_to_cutout_sticker(self, *args: Any, **kwargs: Any) -> Any: ...

        async def media_delete(self, *args: Any, **kwargs: Any) -> Any: ...

        async def media_id(self, *args: Any, **kwargs: Any) -> Any: ...

        async def media_info(self, *args: Any, **kwargs: Any) -> Any: ...

        async def media_info_gql(self, *args: Any, **kwargs: Any) -> Any: ...

        def media_pk(self, *args: Any, **kwargs: Any) -> Any: ...

        async def media_seen(self, *args: Any, **kwargs: Any) -> Any: ...

        def parse_authorization(self, *args: Any, **kwargs: Any) -> Dict[str, Any]: ...

        def _configure_public_transport(self, *args: Any, **kwargs: Any) -> Any: ...

        def _default_public_user_agent(self, *args: Any, **kwargs: Any) -> str: ...

        def _normalize_public_transport(self, *args: Any, **kwargs: Any) -> str: ...

        async def password_encrypt(self, *args: Any, **kwargs: Any) -> str: ...

        async def photo_download_by_url(self, *args: Any, **kwargs: Any) -> Any: ...

        async def photo_download_by_url_origin(self, *args: Any, **kwargs: Any) -> Any: ...

        async def photo_rupload(self, *args: Any, **kwargs: Any) -> Any: ...

        async def private_graphql_query_request(self, *args: Any, **kwargs: Any) -> Any: ...

        async def private_graphql_request(self, *args: Any, **kwargs: Any) -> Any: ...

        async def private_request(self, *args: Any, **kwargs: Any) -> Any: ...

        async def public_a1_request(self, *args: Any, **kwargs: Any) -> Any: ...

        async def public_doc_id_graphql_request(self, *args: Any, **kwargs: Any) -> Any: ...

        async def public_graphql_request(self, *args: Any, **kwargs: Any) -> Any: ...

        async def public_request(self, *args: Any, **kwargs: Any) -> Any: ...

        def request_log(self, *args: Any, **kwargs: Any) -> Any: ...

        def set_country(self, *args: Any, **kwargs: Any) -> Any: ...

        def set_country_code(self, *args: Any, **kwargs: Any) -> Any: ...

        def set_ig_u_rur(self, *args: Any, **kwargs: Any) -> Any: ...

        def set_ig_www_claim(self, *args: Any, **kwargs: Any) -> Any: ...

        def set_locale(self, *args: Any, **kwargs: Any) -> Any: ...

        def set_timezone_offset(self, *args: Any, **kwargs: Any) -> Any: ...

        def set_user_agent(self, *args: Any, **kwargs: Any) -> Any: ...

        async def top_search(self, *args: Any, **kwargs: Any) -> Any: ...

        async def track_download_by_url(self, *args: Any, **kwargs: Any) -> Any: ...

        async def user_info_v1(self, *args: Any, **kwargs: Any) -> Any: ...

        async def user_short_gql(self, *args: Any, **kwargs: Any) -> Any: ...

        async def video_download(self, *args: Any, **kwargs: Any) -> Any: ...

        async def video_download_by_url(self, *args: Any, **kwargs: Any) -> Any: ...

        async def video_download_by_url_origin(self, *args: Any, **kwargs: Any) -> Any: ...

        async def video_rupload(self, *args: Any, **kwargs: Any) -> Any: ...

        async def video_upload_to_direct(self, *args: Any, **kwargs: Any) -> Any: ...

        def with_action_data(self, *args: Any, **kwargs: Any) -> Dict[str, Any]: ...

        def with_default_data(self, *args: Any, **kwargs: Any) -> Dict[str, Any]: ...

        def with_extra_data(self, *args: Any, **kwargs: Any) -> Dict[str, Any]: ...

        def with_query_params(self, *args: Any, **kwargs: Any) -> Dict[str, Any]: ...

else:

    class ClientMixin:
        pass
